language: objective-c
osx_image: xcode7.2
before_install:
- git submodule update --init --recursive
- gem install cocoapods

script:

#build the demo app (Git Submodule)

- xctool -workspace "ShareKit Demo App.xcworkspace" -scheme "ShareKit Demo App" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

#build the demo app (CocoaPods)

- xctool -workspace "ShareKit Demo App.xcworkspace" -scheme "ShareKit Demo App (CocoaPods)" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO