language: objective-c
#xcode_workspace: "ShareKit Demo App.xcworkspace"
#xcode_sdk:
#xcode_scheme: "ShareKit Demo App"

before_install:
- git submodule update --init --recursive

script:

#build the demo app (Git Submodule)

- xctool -workspace "ShareKit Demo App.xcworkspace" -scheme "ShareKit Demo App" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

#build the demo app (CocoaPods)

- xctool -workspace "ShareKit Demo App.xcworkspace" -scheme "ShareKit Demo App (CocoaPods)" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO